### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by StanPlatinum** [jaebaek/SGX-Shield#7]
Dear Jaebaek,

This is Weijie. Big fan! I found your SGX-Shield work which is brilliant and I tried it.

During the sgx sdk and llvm installing, everything went well. And I also built the program under the 'program' directory successfully. However, when I went to the loader and make, the following error occured...

/usr/bin/ld: App/attack.o: relocation R_X86_64_32S against symbol `stack_for_attack' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:204: recipe for target 'app' failed

Do you have any idea how this happened?

Any help is appreciated. Thanks in advance!

**Comment by lpjlwj** [comment]
I have fixed this problem. It seems a linking issue. Specifically, anyone wants to use the demo should modify the Makefile under the /loader dir.

Details can be found https://github.com/lpjlwj/SGX-Shield/blob/master/loader/Makefile#L206

**Comment by tonitick** [comment]
Hi @StanPlatinum ,
I encounter the same issue and link is inaccessible. Could you please specify the changes you made to the makefile? Thanks so much.

**Comment by StanPlatinum** [comment]
@tonitick Sorry I cannot remember clearly and the repo was gone...

Can you check the file in 
https://github.com/StanPlatinum/Deflection/blob/master/loader/Makefile_template4checker ?
Let me know if that helps ...

**Comment by xmhuangzhen** [comment]
> @tonitick Sorry I cannot remember clearly and the repo was gone...
> 
> Can you check the file in https://github.com/StanPlatinum/Deflection/blob/master/loader/Makefile_template4checker ? Let me know if that helps ...

Hi @StanPlatinum , I'm sorry that the file doesn't work. When I make, the following errors occurred...


GEN  =>  App/Enclave_u.c
CC   <=  App/enclave.c
CXX  <=  App/App.cpp
-m64 -O0 -g -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lpthread -lsgx_uae_service
#@g++ -static App/Enclave_u.o App/App.o -o app -Wl,-Bdynamic -m64 -O0 -g -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lpthread  -lsgx_uae_service 
LINK =>  app
GEN  =>  Enclave/Enclave_t.c
CC   <=  Enclave/enclave.c
g++ -m64 -O0 -g -nostdinc -fvisibility=hidden -fpie -fstack-protector -IInclude -IEnclave -I/opt/intel/sgxsdk/include -I/opt/intel/sgxsdk/include/tlibc -I/opt/intel/sgxsdk/include/stlport -I/include -I/libelf -I/install/include -I/sdk/trts -I/common/inc/internal -std=c++03 -nostdinc++ -DLD_DEBUG -c Enclave/Enclave.cpp -o Enclave/Enclave.o
In file included from Enclave/Enclave.cpp:12:0:
Enclave/Enclave.h:43:6: warning: declaration of ‘void printf(const char*, ...)’ conflicts with built-in declaration ‘int printf(const char*, ...)’ [-Wbuiltin-declaration-mismatch]
 void printf(const char *fmt, ...);
      ^~~~~~
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: Enclave/Enclave.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
CXX  <=  Enclave/Enclave.cpp
#@g++ Enclave/Enclave_t.o Enclave/Enclave.o -o enclave.so -m64 -O0 -g -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -L/opt/intel/sgxsdk/lib64 -Wl,--whole-archive -lsgx_trts -Wl,--no-whole-archive -Wl,--start-group -lsgx_tstdc -lsgx_tcxx -lsgx_tcrypto -lsgx_tservice -Wl,--end-group -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie,-eenclave_entry -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0 -Wl,--version-script=Enclave/Enclave.lds Enclave/define_symbols.lds
#checker part added by W
/usr/local/bin/ld: cannot find -lelf_static
/usr/local/bin/ld: cannot find -ldbg_capstone_static
/usr/local/bin/ld: cannot find -lz_static
/usr/local/bin/ld: cannot find -lc_static
/usr/local/bin/ld: warning: Enclave/define_symbols.lds contains output sections; did you forget -T?
collect2: error: ld returned 1 exit status
Makefile:238: recipe for target 'enclave.so' failed
make: *** [enclave.so] Error 1


Do you have any idea? Thanks in advance.

**Comment by StanPlatinum** [comment]
@xmhuangzhen 

errors here.
```
/usr/local/bin/ld: cannot find -lelf_static
/usr/local/bin/ld: cannot find -ldbg_capstone_static
/usr/local/bin/ld: cannot find -lz_static
/usr/local/bin/ld: cannot find -lc_static
```

You must include those libs. Those are used in my project (Deflection), not in SGX-Shield. So you cannot use my Makefile in this SGX-Shield project.

Anyway, I think this might be too complex to read my Makefile and do changes to SGX-Shield's.

But the first thing is still to understand how Makefile works...

**Comment by huwenao** [comment]
> Hi @StanPlatinum , I encounter the same issue and link is inaccessible. Could you please specify the changes you made to the makefile? Thanks so much.

You can just add `-no-pie` to the link compilation options.
